/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.hdsb.gwss.ics4c;

import javax.swing.DefaultListModel;

/**
 *
 * @author Nick
 */
public class MusicLibrary extends javax.swing.JFrame {

    DefaultListModel libraryDataList;
    DefaultListModel playlistDataList;

    /**
     * Creates new form MusicLibrary
     */
    public MusicLibrary() {
        initComponents();
        libraryDataList = new DefaultListModel();
        libraryList.setModel(libraryDataList);
        playlistDataList = new DefaultListModel();
        playlistList.setModel(playlistDataList);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        musicLibrarytxt = new javax.swing.JLabel();
        songTitleTxt = new javax.swing.JLabel();
        songTitleBox = new javax.swing.JTextField();
        addToLibraryButton = new javax.swing.JButton();
        libraryTxt = new javax.swing.JLabel();
        playlistTxt = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        libraryList = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        playlistList = new javax.swing.JList();
        movePlaylistButton = new javax.swing.JButton();
        moveLibraryButton = new javax.swing.JButton();
        sortPlaylistButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 255, 255));

        musicLibrarytxt.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        musicLibrarytxt.setText("Music Library");

        songTitleTxt.setText("Enter Song Title");

        addToLibraryButton.setText("Add to Library");
        addToLibraryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToLibraryButtonActionPerformed(evt);
            }
        });

        libraryTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        libraryTxt.setText("Library");

        playlistTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        playlistTxt.setText("Playlist");

        jScrollPane1.setViewportView(libraryList);

        jScrollPane2.setViewportView(playlistList);

        movePlaylistButton.setText(">>>");
        movePlaylistButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movePlaylistButtonActionPerformed(evt);
            }
        });

        moveLibraryButton.setText("<<<");
        moveLibraryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveLibraryButtonActionPerformed(evt);
            }
        });

        sortPlaylistButton.setText("Sort Playlist");
        sortPlaylistButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortPlaylistButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(libraryTxt)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(songTitleTxt)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(songTitleBox))
                                    .addComponent(musicLibrarytxt))))
                        .addGap(94, 94, 94))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(addToLibraryButton)
                                .addComponent(playlistTxt))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(movePlaylistButton)
                                    .addComponent(moveLibraryButton))
                                .addGap(15, 15, 15)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(sortPlaylistButton)))
                        .addContainerGap(33, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(musicLibrarytxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(songTitleTxt)
                    .addComponent(songTitleBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addToLibraryButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(libraryTxt)
                    .addComponent(playlistTxt))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1)
                                    .addComponent(jScrollPane2)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(movePlaylistButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(moveLibraryButton)))
                        .addGap(0, 32, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sortPlaylistButton)
                        .addGap(100, 100, 100))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addToLibraryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToLibraryButtonActionPerformed
        // TODO add your handling code here:
        libraryDataList.add(libraryDataList.getSize(), songTitleBox.getText());
        libraryList.setModel(libraryDataList);
    }//GEN-LAST:event_addToLibraryButtonActionPerformed

    private void movePlaylistButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movePlaylistButtonActionPerformed
        // TODO add your handling code here:
        libraryDataList = (DefaultListModel) libraryList.getModel();
        playlistDataList = (DefaultListModel) playlistList.getModel();

        int x = libraryList.getSelectedIndex();
        String song = (String) libraryDataList.getElementAt(x);

        playlistDataList.add(playlistDataList.getSize(), song);
        playlistList.setModel(playlistDataList);
    }//GEN-LAST:event_movePlaylistButtonActionPerformed

    private void moveLibraryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveLibraryButtonActionPerformed
        // TODO add your handling code here:
        libraryDataList = (DefaultListModel) libraryList.getModel();
        playlistDataList = (DefaultListModel) playlistList.getModel();

        int x = playlistList.getSelectedIndex();
        String song = (String) playlistDataList.remove(x);

        //playlistDataList.add(playlistDataList.getSize(), song);
        playlistList.setModel(playlistDataList);
    }//GEN-LAST:event_moveLibraryButtonActionPerformed

    private void sortPlaylistButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortPlaylistButtonActionPerformed
        // TODO add your handling code here:
        

        for (int pass = 0; pass < playlistDataList.size(); pass++) {
            for (int i = 0; i < playlistDataList.size() - 1; i++) {
                String name1 = (String) playlistDataList.get(i);
                String name2 = (String) playlistDataList.get(i + 1);

                if (name1.compareTo(name2) > 0) {
                    String name = (String) playlistDataList.remove(i);
                    playlistDataList.add(i + 1, name);
                }
            }
            playlistList.setModel(playlistDataList);
        }
    }//GEN-LAST:event_sortPlaylistButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MusicLibrary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MusicLibrary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MusicLibrary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MusicLibrary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MusicLibrary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addToLibraryButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList libraryList;
    private javax.swing.JLabel libraryTxt;
    private javax.swing.JButton moveLibraryButton;
    private javax.swing.JButton movePlaylistButton;
    private javax.swing.JLabel musicLibrarytxt;
    private javax.swing.JList playlistList;
    private javax.swing.JLabel playlistTxt;
    private javax.swing.JTextField songTitleBox;
    private javax.swing.JLabel songTitleTxt;
    private javax.swing.JButton sortPlaylistButton;
    // End of variables declaration//GEN-END:variables
}
