/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package edu.hdsb.gwss.ics4c.u4;

import java.awt.Color;
import java.math.BigDecimal;
import javax.swing.BorderFactory;

/**
 *
 * @author Nick
 */
public class AverageCalculator extends javax.swing.JFrame {
    


    /**
     * Creates new form AverageCalculator
     */
    public AverageCalculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        averageCalculatorTxt = new javax.swing.JLabel();
        grade1Txt = new javax.swing.JLabel();
        grade2Txt = new javax.swing.JLabel();
        grade3Txt = new javax.swing.JLabel();
        grade4Txt = new javax.swing.JLabel();
        averageBtn = new javax.swing.JButton();
        averageTxt = new javax.swing.JLabel();
        averageResults = new javax.swing.JLabel();
        grade1Box = new javax.swing.JTextField();
        grade2Box = new javax.swing.JTextField();
        grade3Box = new javax.swing.JTextField();
        grade4Box = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        averageCalculatorTxt.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        averageCalculatorTxt.setText("Average Calculator");

        grade1Txt.setText("Grade 1");

        grade2Txt.setText("Grade 2");

        grade3Txt.setText("Grade 3");

        grade4Txt.setText("Grade 4");

        averageBtn.setText("Calculator Average");
        averageBtn.setToolTipText("");
        averageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                averageBtnActionPerformed(evt);
            }
        });

        averageTxt.setText("Average");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(averageCalculatorTxt))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(grade2Txt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(grade2Box))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(grade1Txt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(grade1Box))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(grade3Txt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(grade3Box))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(grade4Txt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(grade4Box))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(averageTxt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(averageResults, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(averageBtn))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(averageCalculatorTxt)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(grade1Txt)
                    .addComponent(grade1Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(grade2Txt)
                    .addComponent(grade2Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(grade3Txt)
                    .addComponent(grade3Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(grade4Txt)
                    .addComponent(grade4Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(averageBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(averageTxt)
                    .addComponent(averageResults, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void averageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_averageBtnActionPerformed
        boolean valid = true;
        int[] marks = new int[4];
        try {
            marks[0] = Integer.parseInt( grade1Box.getText() );
            grade1Box.setBorder( null );
        } catch (Exception e) {
            valid = false;
            grade1Box.setBorder( BorderFactory.createLineBorder(Color.red, 2 ));
        }
         try {
            marks[1] = Integer.parseInt( grade2Box.getText() );
            grade2Box.setBorder( null );
        } catch (Exception e) {
            valid = false;
            grade2Box.setBorder( BorderFactory.createLineBorder(Color.red, 2 ));
        }
         try {
            marks[2] = Integer.parseInt( grade3Box.getText() );
            grade3Box.setBorder( null );
        } catch (Exception e) {
            valid = false;
            grade3Box.setBorder( BorderFactory.createLineBorder(Color.red, 2 ));
        }
         try {
            marks[3] = Integer.parseInt( grade4Box.getText() );
            grade4Box.setBorder( null );
        } catch (Exception e) {
            valid = false;
            grade4Box.setBorder( BorderFactory.createLineBorder(Color.red, 2 ));
        }
         if(!valid){
             averageResults.setText("error please enter values again");
         }
       
        
        if( valid ) {
            double average = AverageCalculatorClass.average(marks);
            averageResults.setText("" + average);
        }
    }//GEN-LAST:event_averageBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AverageCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AverageCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AverageCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AverageCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AverageCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton averageBtn;
    private javax.swing.JLabel averageCalculatorTxt;
    private javax.swing.JLabel averageResults;
    private javax.swing.JLabel averageTxt;
    private javax.swing.JTextField grade1Box;
    private javax.swing.JLabel grade1Txt;
    private javax.swing.JTextField grade2Box;
    private javax.swing.JLabel grade2Txt;
    private javax.swing.JTextField grade3Box;
    private javax.swing.JLabel grade3Txt;
    private javax.swing.JTextField grade4Box;
    private javax.swing.JLabel grade4Txt;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
