/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.hdsb.gwss.ics4c.u4;

import java.awt.Color;
import javax.swing.BorderFactory;

/**
 *
 * @author Nick
 */
public class TicketMasterGUI extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public TicketMasterGUI() {
        initComponents();
        ticketsRemaingBox.setText("" + TicketMasterClass.tier1remaming);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tierBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        numberOfTickets = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        buyTicketsbtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        ticketsRemaingBox = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ticketPriceBox = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tierBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tier 1", "Tier 2", "Tier 3", "Tier 4" }));
        tierBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tierBoxActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Ticket Master");

        numberOfTickets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberOfTicketsActionPerformed(evt);
            }
        });

        jLabel2.setText("Number of Tickets");

        buyTicketsbtn.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        buyTicketsbtn.setText("Buy Tickets");
        buyTicketsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyTicketsbtnActionPerformed(evt);
            }
        });

        jLabel3.setText("Tickets remaing");

        jLabel4.setText("Ticket Price");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(buyTicketsbtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(ticketsRemaingBox, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tierBox, 0, 121, Short.MAX_VALUE)
                            .addComponent(numberOfTickets)
                            .addComponent(ticketPriceBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tierBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numberOfTickets, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                    .addComponent(ticketPriceBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(buyTicketsbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ticketsRemaingBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numberOfTicketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberOfTicketsActionPerformed

    }//GEN-LAST:event_numberOfTicketsActionPerformed

    private void buyTicketsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyTicketsbtnActionPerformed
        try {
            //get the total amount for tier 1 the tickets cost if not enough print out Not enough tickets left
            if (tierBox.getSelectedIndex() == 0) {
                if (TicketMasterClass.tier1remaming >= Integer.parseInt(numberOfTickets.getText())) {
                    TicketMasterClass.tier1remaming = TicketMasterClass.tier1remaming - Integer.parseInt(numberOfTickets.getText());
                    ticketsRemaingBox.setText("" + TicketMasterClass.tier1remaming);
                    int ticketPrice = TicketMasterClass.tier1Price * Integer.parseInt(numberOfTickets.getText());
                    ticketPriceBox.setText("$" + ticketPrice);
                } else {
                    ticketPriceBox.setText("Not enough tickets left");

                }
                 //get the total amount for tier 2 the tickets cost if not enough print out Not enough tickets left
            } else if (tierBox.getSelectedIndex() == 1) {
                if (TicketMasterClass.tier2remaming >= Integer.parseInt(numberOfTickets.getText())) {
                    TicketMasterClass.tier2remaming = TicketMasterClass.tier2remaming - Integer.parseInt(numberOfTickets.getText());
                    ticketsRemaingBox.setText("" + TicketMasterClass.tier2remaming);
                    int ticketPrice = TicketMasterClass.tier2Price * Integer.parseInt(numberOfTickets.getText());
                    ticketPriceBox.setText("$" + ticketPrice);
                } else {
                    ticketPriceBox.setText("Not enough tickets left");

                }
                 //get the total amount for tier 3 the tickets cost if not enough print out Not enough tickets left
            } else if (tierBox.getSelectedIndex() == 2) {
                if (TicketMasterClass.tier3remaming >= Integer.parseInt(numberOfTickets.getText())) {
                    TicketMasterClass.tier3remaming = TicketMasterClass.tier3remaming - Integer.parseInt(numberOfTickets.getText());
                    ticketsRemaingBox.setText("" + TicketMasterClass.tier3remaming);
                    int ticketPrice = TicketMasterClass.tier3Price * Integer.parseInt(numberOfTickets.getText());
                    ticketPriceBox.setText("$" + ticketPrice);
                }
                 //get the total amount for tier 4 the tickets cost if not enough print out Not enough tickets left
            } else {
                if (TicketMasterClass.tier4remaming >= Integer.parseInt(numberOfTickets.getText())) {
                    TicketMasterClass.tier4remaming = TicketMasterClass.tier4remaming - Integer.parseInt(numberOfTickets.getText());
                    ticketsRemaingBox.setText("" + TicketMasterClass.tier4remaming);
                    int ticketPrice = TicketMasterClass.tier4Price * Integer.parseInt(numberOfTickets.getText());
                    ticketPriceBox.setText("$" + ticketPrice);
                } else {
                    ticketPriceBox.setText("Not enough tickets left");

                }
            }
            //if user enters a string make borader red
        } catch (Exception e) {
            numberOfTickets.setBorder(BorderFactory.createLineBorder(Color.red, 2));
        }

    }//GEN-LAST:event_buyTicketsbtnActionPerformed

    private void tierBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tierBoxActionPerformed
//print out the amount of each tickets
        if (tierBox.getSelectedIndex() == 0) {

            ticketsRemaingBox.setText("" + TicketMasterClass.tier1remaming);

        } else if (tierBox.getSelectedIndex() == 1) {

            ticketsRemaingBox.setText("" + TicketMasterClass.tier2remaming);

        } else if (tierBox.getSelectedIndex() == 2) {

            ticketsRemaingBox.setText("" + TicketMasterClass.tier3remaming);

        } else {

            ticketsRemaingBox.setText("" + TicketMasterClass.tier4remaming);

        }

    }//GEN-LAST:event_tierBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicketMasterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicketMasterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicketMasterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicketMasterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicketMasterGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buyTicketsbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField numberOfTickets;
    private javax.swing.JLabel ticketPriceBox;
    private javax.swing.JLabel ticketsRemaingBox;
    private javax.swing.JComboBox tierBox;
    // End of variables declaration//GEN-END:variables
}
