/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.hdsb.gwss.ics3u.nick;

/**
 *
 * @author Nick
 */
public class SlotMachineGUI extends javax.swing.JApplet {

    static int numberOfCoins = 50;

    /**
     * Initializes the applet SlotMachineGUI
     */
    @Override
    public void init() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SlotMachineGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SlotMachineGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SlotMachineGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SlotMachineGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the applet */
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        wheelDisplay1 = new javax.swing.JLabel();
        wheelDisplay2 = new javax.swing.JLabel();
        wheelDisplay3 = new javax.swing.JLabel();
        spinButtion = new javax.swing.JButton();
        Coins = new javax.swing.JLabel();
        winningSlot = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        WinCoins = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(51, 204, 0));

        wheelDisplay1.setFont(new java.awt.Font("Tahoma", 0, 200)); // NOI18N
        wheelDisplay1.setForeground(new java.awt.Color(0, 0, 255));
        wheelDisplay1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wheelDisplay1.setText("0");
        wheelDisplay1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));

        wheelDisplay2.setFont(new java.awt.Font("Tahoma", 0, 200)); // NOI18N
        wheelDisplay2.setForeground(new java.awt.Color(255, 255, 0));
        wheelDisplay2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wheelDisplay2.setText("0");
        wheelDisplay2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));

        wheelDisplay3.setFont(new java.awt.Font("Tahoma", 0, 200)); // NOI18N
        wheelDisplay3.setForeground(new java.awt.Color(255, 0, 0));
        wheelDisplay3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wheelDisplay3.setText("0");
        wheelDisplay3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));

        spinButtion.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        spinButtion.setForeground(new java.awt.Color(0, 51, 255));
        spinButtion.setText("SPIN!!");
        spinButtion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spinButtionActionPerformed(evt);
            }
        });

        Coins.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        Coins.setForeground(new java.awt.Color(204, 204, 0));
        Coins.setText("COINS: 50");

        winningSlot.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        winningSlot.setForeground(new java.awt.Color(153, 255, 255));
        winningSlot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        winningSlot.setText("Winning Slot Machine!!");

        WinCoins.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        WinCoins.setForeground(new java.awt.Color(51, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(wheelDisplay1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Coins)
                        .addGap(241, 241, 241)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(spinButtion, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                    .addComponent(wheelDisplay2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(wheelDisplay3, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(WinCoins, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(winningSlot, javax.swing.GroupLayout.DEFAULT_SIZE, 1103, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(winningSlot, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(wheelDisplay1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(wheelDisplay2, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(wheelDisplay3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(WinCoins, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(53, 53, 53)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Coins)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(spinButtion, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(277, 277, 277))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void spinButtionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spinButtionActionPerformed
        int wheel1;
        int wheel2;
        int wheel3;

        boolean keepPlaying = true;

        wheel1 = (int) (Math.random() * 3) + 1;
        wheel2 = (int) (Math.random() * 3) + 1;
        wheel3 = (int) (Math.random() * 3) + 1;

        wheelDisplay1.setText("" + wheel1);
        wheelDisplay2.setText("" + wheel2);
        wheelDisplay3.setText("" + wheel3);

        System.out.println(wheel1);
        System.out.println(wheel2);
        System.out.println(wheel3);

        if (wheel1 == wheel2 && wheel2 == wheel3 && wheel3 == 1) {
            numberOfCoins = numberOfCoins + 4;
            WinCoins.setText("You won 4 coins");
        } else if (wheel1 == wheel2 && wheel2 == wheel3 && wheel3 == 2) {
            numberOfCoins = numberOfCoins + 6;
            WinCoins.setText("You won 6 coins");
        } else if (wheel1 == wheel2 && wheel2 == wheel3 && wheel3 == 3) {
            numberOfCoins = numberOfCoins + 8;
            WinCoins.setText("You won 8 coins");
        } else if (wheel1 == wheel2 && wheel2 == wheel3 && wheel3 == 4) {
            numberOfCoins = numberOfCoins + 10;
            WinCoins.setText("You won 10 cons");
        } else {
            numberOfCoins = numberOfCoins - 1;
            System.out.println("Spingain");
            System.out.println("You have " + numberOfCoins + " Coins");
             WinCoins.setText("");
        }

        Coins.setText("" + numberOfCoins);

        if (numberOfCoins <= 0) {
            Coins.setText("GOOD BYE");
            spinButtion.setEnabled(false);
        }
    }//GEN-LAST:event_spinButtionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Coins;
    private javax.swing.JLabel WinCoins;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton spinButtion;
    private javax.swing.JLabel wheelDisplay1;
    private javax.swing.JLabel wheelDisplay2;
    private javax.swing.JLabel wheelDisplay3;
    private javax.swing.JLabel winningSlot;
    // End of variables declaration//GEN-END:variables
}
