/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.hdsb.gwss.ics4c.pt;

import java.awt.Color;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.BorderFactory;
import nu.xom.Document;
import nu.xom.Element;

/**
 *
 * @author Nick
 */
public class studentGUI extends javax.swing.JFrame {

    Element students = new Element("Students");
    Document doc = new Document(students);

    /**
     * Creates new form studentGUI
     */
    public studentGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        studentTxt = new javax.swing.JLabel();
        nameTxt = new javax.swing.JLabel();
        ageTxt = new javax.swing.JLabel();
        mark1Txt = new javax.swing.JLabel();
        mark2Txt = new javax.swing.JLabel();
        mark3Txt = new javax.swing.JLabel();
        mark4Txt = new javax.swing.JLabel();
        nameBox = new javax.swing.JTextField();
        ageBox = new javax.swing.JTextField();
        mark1Box = new javax.swing.JTextField();
        mark2Box = new javax.swing.JTextField();
        mark3Box = new javax.swing.JTextField();
        mark4Box = new javax.swing.JTextField();
        addStudentButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        studentTxt.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        studentTxt.setText("Student");

        nameTxt.setText("Name:");

        ageTxt.setText("Age:");

        mark1Txt.setText("Mark 1:");

        mark2Txt.setText("Mark 2:");

        mark3Txt.setText("Mark 3:");

        mark4Txt.setText("Mark 4:");

        nameBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameBoxActionPerformed(evt);
            }
        });

        addStudentButton.setText("ADD STUDENT");
        addStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(studentTxt))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(mark1Txt)
                            .addComponent(ageTxt)
                            .addComponent(nameTxt)
                            .addComponent(mark2Txt)
                            .addComponent(mark3Txt)
                            .addComponent(mark4Txt))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nameBox)
                            .addComponent(ageBox)
                            .addComponent(mark1Box)
                            .addComponent(mark2Box)
                            .addComponent(mark3Box)
                            .addComponent(mark4Box, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(addStudentButton)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(studentTxt)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTxt)
                    .addComponent(nameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ageTxt)
                    .addComponent(ageBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mark1Txt)
                    .addComponent(mark1Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mark2Txt)
                    .addComponent(mark2Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mark3Txt)
                    .addComponent(mark3Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mark4Txt)
                    .addComponent(mark4Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addStudentButton)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameBoxActionPerformed

    private void addStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentButtonActionPerformed
        StudentClass student = new StudentClass();
        int[] marks = new int[4];
        boolean valid = true;
        nameBox.setBorder(BorderFactory.createLineBorder(Color.gray, 0));
        if (nameBox.getText().length() == 0) {

            nameBox.setBorder(BorderFactory.createLineBorder(Color.red, 2));
            valid = false;
        }
        try {
            student.setAge(Integer.parseInt(ageBox.getText()));
            ageBox.setBorder(BorderFactory.createLineBorder(Color.gray, 0));
        } catch (Exception e) {
            ageBox.setBorder(BorderFactory.createLineBorder(Color.red, 2));
            valid = false;
        }

        try {
            marks[0] = Integer.parseInt(mark1Box.getText());
            mark1Box.setBorder(BorderFactory.createLineBorder(Color.gray, 0));
        } catch (Exception e) {
            mark1Box.setBorder(BorderFactory.createLineBorder(Color.red, 2));
            valid = false;
        }
        try {
            marks[1] = Integer.parseInt(mark2Box.getText());
            mark2Box.setBorder(BorderFactory.createLineBorder(Color.gray, 0));
        } catch (Exception e) {
            mark2Box.setBorder(BorderFactory.createLineBorder(Color.red, 2));
            valid = false;
        }
        try {
            marks[2] = Integer.parseInt(mark3Box.getText());
            mark3Box.setBorder(BorderFactory.createLineBorder(Color.gray, 0));
        } catch (Exception e) {
            mark3Box.setBorder(BorderFactory.createLineBorder(Color.red, 2));
            valid = false;
        }
        try {
            marks[3] = Integer.parseInt(mark4Box.getText());
            mark4Box.setBorder(BorderFactory.createLineBorder(Color.gray, 0));
        } catch (Exception e) {
            mark4Box.setBorder(BorderFactory.createLineBorder(Color.red, 2));
            valid = false;
        }

        if (valid = true) {
            student.setMarks(marks);
            addStudentToXML(student);
        }

    }//GEN-LAST:event_addStudentButtonActionPerformed

    public void addStudentToXML(StudentClass student) {

        Element studentElement = new Element("student");

        Element name = new Element("name");
        name.appendChild(student.getName());
        Element age = new Element("age");
        age.appendChild(student.getAge() + "");
        Element mark1 = new Element("mark1");

        int[] marks = student.getMarks();
        double average = (marks[0] + marks[1] + marks[2] + marks[3]) / 4;
        Double.toString(average);
        mark1.appendChild("" + marks[0]);
        Element mark2 = new Element("mark2");
        mark2.appendChild("" + marks[1]);
        Element mark3 = new Element("mark3");
        mark3.appendChild("" + marks[2]);
        Element mark4 = new Element("mark4");
        mark4.appendChild("" + marks[3]);
        Element averageElement = new Element("average");
        averageElement.appendChild("" + average);

        studentElement.appendChild(name);
        studentElement.appendChild(age);
        studentElement.appendChild(mark1);
        studentElement.appendChild(mark2);
        studentElement.appendChild(mark3);
        studentElement.appendChild(mark4);
        studentElement.appendChild(averageElement);

        //root it back so it shows in xml
        students.appendChild(studentElement);
        try {
            //writes to friens.xml
            FileWriter fw = new FileWriter("studentClass.xml");
            BufferedWriter bw = new BufferedWriter(fw);
            bw.write(doc.toXML());

            bw.close();
        } catch (IOException ex) {
            System.err.println(ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addStudentButton;
    private javax.swing.JTextField ageBox;
    private javax.swing.JLabel ageTxt;
    private javax.swing.JTextField mark1Box;
    private javax.swing.JLabel mark1Txt;
    private javax.swing.JTextField mark2Box;
    private javax.swing.JLabel mark2Txt;
    private javax.swing.JTextField mark3Box;
    private javax.swing.JLabel mark3Txt;
    private javax.swing.JTextField mark4Box;
    private javax.swing.JLabel mark4Txt;
    private javax.swing.JTextField nameBox;
    private javax.swing.JLabel nameTxt;
    private javax.swing.JLabel studentTxt;
    // End of variables declaration//GEN-END:variables
}
